README.md

README.mdにGithub IDとプロフィールのURLを追記しました。

READMEに自己紹介を追加

---

client/src/assets/base.css

chore: 色変数を追加

---

server/internal/games/internal/events/events.go
server/internal/games/internal/events/ws/ws.go
server/internal/games/ws.go
server/main.go

:sparkles: /games/:gameID/ws の実装

---

client/src/components/CommonButton.vue

feat: 汎用ボタンコンポーネント`CommonButton`を作成

---

client/src/assets/main.css
client/src/components/PointResult.vue
client/src/pages/HomePage.vue

スコア表示画面を作成しました

---

client/src/lib/gameLogic.ts
client/src/lib/type.ts

feat/ gameinfo の実装を追加

---

server/internal/cards/internal/events/ws/updated.go
server/internal/core/corews/filter.go
server/internal/core/corews/json.go
server/internal/games/internal/domain/game.go
server/internal/games/internal/domain/player.go
server/internal/games/internal/events/events.go
server/internal/games/internal/events/ws/score_updated.go
server/internal/games/internal/repository/db/db.go
server/internal/games/internal/repository/db/game.go
server/internal/games/internal/repository/db/player.go
server/internal/games/internal/repository/repository.go
server/internal/games/score_updated.go
server/internal/games/ws.go
server/main.go

fix #47
- **:sparkles: ScoreUpdatedのミドルウェア実装**
- **:sparkles: repositoryの実装**
- **:sparkles: wsイベントの発行を実装**
- **:sparkles: ミドルウェアの登録**
- **:bug: クエリのテーブル名修正**

scoreUpdatedイベントの実装

---

client/src/App.vue
client/src/assets/main.css

chore: 共通レイアウトの整理

---

client/src/pages/HomePage.vue

ホーム画面のレイアウトを作りました

---

client/src/pages/ResultPage.vue

リザルト画面のボタンを押した際の挙動を追加

---

docs/api.md
server/internal/games/internal/events/events.go
server/internal/games/internal/events/ws/turn_ended.go
server/internal/games/turn.go

fix #48
- **:sparkles: TurnEndedの実装**
- **:sparkles: wsのTurnEndedイベントを追加**
- **:memo: ドキュメントを更新**

turnEndedイベントの実装

---

client/src/components/CommonButton.vue
client/src/components/ExpressionCards.vue
client/src/components/HandCardCounter.vue
client/src/components/HandCards.vue
client/src/components/ScoreBoard.vue
client/src/pages/GamePage.vue

close #87 
併せて`gameState`オブジェクトから状態を引いてくるようにしました

feat: 試合ページのレイアウトを作成

---

server/internal/games/internal/events/events.go
server/internal/games/start.go

:sparkles: gameStartedでturnTotalを送る

---

client/src/lib/gameLogic.ts
client/src/lib/type.ts

chore: 総ターン数を`GameInfo`で保持するように変更

---

client/src/pages/HomePage.vue

feat: ゲームマッチング機能

---

client/src/components/GameCard.vue
client/src/components/HandCards.vue
client/src/pages/GamePage.vue

close #108 
useCardは動きました
- 選択したカードはグレーアウトするようになりました

feat: 試合ページのカードをクリックで操作できるように変更

---

server/internal/games/get_result.go
server/internal/games/internal/domain/expression.go
server/internal/games/internal/repository/db/db.go
server/internal/games/internal/repository/db/expression.go
server/internal/games/internal/repository/repository.go

- **:sparkles: GetGameResultの実装**
- **:sparkles: respositoryでexpressionsの取得を実装**

gerResultの実装

---

client/src/pages/GamePage.vue

feat: TurnTimerに実際のターン数と制限時間を反映

---

server/internal/games/game_auth.go
server/main.go

fix #65
- **:sparkles: ゲームに参加するユーザーか調べる**
- **:sparkles: ルーティングに組み込む**

ゲームに対するプレイヤーの認可

---

client/src/components/TurnTimer.vue
client/src/pages/GamePage.vue

close #158 
- Opponentの場合はタイマーを赤くする
- Opponentの場合はField cardをdisabledにする

feat: 自分のターンで表示を変える

---

server/internal/games/turn_auth.go
server/main.go

fix #66
- **:sparkles: 自分のターン以外リクエストできないミドルウェア**
- **:sparkles: ミドルウェア登録**

turnのミドルウェア実装

---

server/internal/cards/internal/repository/db/db.go
server/internal/cards/internal/repository/repository.go
server/internal/cards/picks.go

- **:sparkles: pickでhand limitを超えないようにする**
- **:adhesive_bandage: transactionを入れる**

pickでhand limitを超えないように

---

client/src/pages/HomePage.vue

feat: タイトルを設定

---

server/internal/items/repository/db/db.go
server/internal/items/repository/repository.go
server/internal/items/usingItem.go

:sparkles: アイテムカードを使う

---

server/internal/expressions/post.go
server/main.go

- **:bug: resultsを取得するAPIを追加**
- **:bug: 式の提出のバグ修正**

resultsのエンドポイントを登録

---

server/internal/cards/picks.go
server/internal/core/coredb/db.go

- **:bug: IncreaseFieldCardsMaxNumberを2回呼んでいたのを修正**
- **:fire: Transaction内のエラーをwrapしないように修正**

Transactionのエラーをwrapしないようにする

---

client/src/pages/GamePage.vue

fix: Hand cardの選択状態がリセットされてしまう問題の修正

---

client/index.html

feat: OGPタグを追加

---

client/src/lib/gameLogic.ts

fix: Hand cards が clear されたときに expression cards も clear する
